name: Qraft
version: 1.0
main: me.quinut.qraft.Qraft
api-version: 1.21
commands:

  randombread:
    description: Manually triggers the bread announcement.
    usage: /randombread
    permission: tracker.randombread
  claimbread:
    description: Claims your random bread.
    usage: /claimbread
